As seen in the "movies2.py" file, there was a failed attempt to create the "movies_test.csv" in the same directory.
